# --- Stage 1 : Builder ---
FROM node:18-alpine AS builder
WORKDIR /app
COPY package.json ./
RUN npm install
COPY app.js ./
RUN npm run test

# --- Stage 2 : Production ---
FROM node:18-alpine AS production
WORKDIR /app

RUN adduser -D -u 1001 appuser

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/app.js ./


USER appuser

EXPOSE 3000
CMD ["npm", "start"]
